name: 'CI-CD Pipeline'

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  docker:
    name: "Docker CI"
    runs-on: ubuntu-latest
    
    env:
      REGISTRY: "asp-pdz-ecs"
      
    defaults:
      run:
        shell: bash
        working-directory: ./ecs
        
    steps:
      - name: Checkout
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Dockerhub Login
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          logout: true
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: view
        run: ls -la
        
      - name: Build and push
        uses: docker/build-push-action@v2.6.1
        with:
          context: .
          push: true
          tags: "{{secrets.DOCKERHUB_USERNAME}}/asp-pdz-ecs:latest"
          
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
            
  lambda:
    name: "Lambda CI"
    needs: [docker]
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash
        working-directory: ./lambda
        
    steps:
      - name: Checkout
      - uses: actions/checkout@v2
      
      - name: use node 12
        uses: actions/cache@v2
        with:
          node-version: '12'
          path: '~/.npm'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      
      - name: install dependencies
        run: npm ci

      - name: test
        run: npm test
      
      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r lambda.zip . -x "test*" "coverage*"
      
      - uses: actions/upload-artifact@v2
        with:
          name: lambda.zip
          path: lambda.zip

  terraform:
    name: 'AWS Deployment'
    runs-on: ubuntu-latest
    environment: development
    needs: [lambda, docker]
    
    defaults:
      run:
        shell: bash
        working-directory: ./infra

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - uses: actions/download-artifact@v2
      with:
        name: lambda.zip
        path: infra

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TERRAFORM_API_TOKEN }}
     
    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Plan
      run: terraform plan
      
    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Terraform Apply
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      run: terraform apply -auto-approve
