# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash
        working-directory: ./lambda
        
    steps:
      - uses: actions/checkout@v2
      
      - name: use node 12
        uses: actions/setup-node@v2
        with:
          working-directory: ./lambda
          node-version: '12'
          cache: 'npm'

      - name: install dependencies
        run: npm ci

      - name: test
        run: npm test

      - name: dist
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: 'lambda.zip'
          exclusions: '*test* *coverage*'
